### ISSUE TITLE
v0.0.19 broke TypeScript stories types on combineStories

### ISSUE THREAD

**Issue by jgoux** [storybookjs/testing-react#41] opened 2021-07-23 09:54 UTC
Hello all,

**Describe the bug**
Since v0.0.19, `combineStories` is returning `any` for all the stories : 
![image](https://user-images.githubusercontent.com/1443499/126765515-746223e1-8512-44c6-b214-6b4b169fab33.png)

The component exported here is : 

```tsx
const Template: Story = () => (
  <CreateProjectDrawer>
    <DrawerTrigger as={Button}>Create a project</DrawerTrigger>
  </CreateProjectDrawer>
);

const Default = Template.bind({});
```

**To Reproduce**
1. Export any story
2. Use `combineStories` and you can see the stories are no longer typed

**Expected behavior**
`combineStories` should return typed stories (v0.0.18 here) : 
![image](https://user-images.githubusercontent.com/1443499/126765668-675494e3-992f-47ff-9486-7ffe820947fe.png)

**Screenshots**

**Additional context**
v0.0.18 is the last version where it works, all later release are broken.
I'm using storybook `6.3.5`.

**Comment by neet** [comment] 2021-08-06 17:01
I’ve got the same issue with the latest version 0.0.21. This problem seems to be caused by the mismatching of a peer dependency `@storybook/addons`.

In `@storybook/addons` published as latest on npm, a type named `BaseStoryFn` is not exported.  Since the type definition of `composeStories`'s return value is depending on `BaseStoryFn`, TS could not resolve the proper type and returns any instead.

I could circumvent this issue by installing exact same version of `@storybook/addons` that is specified in the devDependencies of `@storybook/testing-react`.

```
yarn add @storybook/addons@^6.4.0-alpha.17 --dev
```

**Comment by yannbf** [comment] 2021-08-08 20:44
Hey @jgoux @neet, thanks for this discussion and sorry for the inconvenience!

I'm currently in a conumdrum. Support for CSF 3.0 was requested in #31, and in order to properly support it I needed types from storybook 6.4. I didn't think much about it, and now it's difficult to find a solution that both supports the older types AND the new types in the same function. I'm not sure how to do that, so I'd say for now you can take either route:

1 - Downgrade `@storybook/testing-react` to v0.0.18 and fix it until Storybook 6.4 is released and upgrade it when you upgrade Storybook 6.4. The only difference between versions 18 and 21 is CSF3 support.

2 - Upgrade to Storybook 6.4 (e.g. npx sb@next upgrade --prerelease) and it should just work. Not only you get to try cool new features in SB 6.4 but you can give some feedback to Storybook :p

In the meantime, I'll try to think of a solution. If you have any ideas to help, they're greatly appreciated!

**Comment by jgoux** [comment] 2021-08-10 18:53
I think the best course of action would have been to release a major of this package maybe?

I don't know for the others, but we rely heavily on renovate/dependabot to automatically upgrade our deps if they're minor/patch releases, and if this isn't something fixable in those channels then maybe it could be considered a breaking change?

Having to upgrade to a non stable release (6.4) doesn't seem like a proper solution to me (even if I love being at the bleeding edge and testing new things early).

For now we fixed the version to v0.0.18 but I really think you shouldn't be afraid of bumping a major in those situations. 👍

**Comment by yannbf** [comment] 2021-08-15 21:41
Hey @jgoux thanks for your opinion. For now I reverted the support for CSF3 in `v0.0.22` so most users should be able to use it without issues. I'm still thinking about how to approach getting support back, and it might likely be in a major release. Please update and let me know if things went fine!

**Comment by yannbf** [comment] 2021-08-20 15:48
Hey everyone, I just made a prerelease that supports CSF3.

If you're not using CSF3, you should be using `v0.0.22` without any issues.
If you're using CSF3, please install `v1.0.0-next.0` and try it out, but keep in mind you need Storybook 6.4 if you're using typescript.

I'll be closing this issue, and feel free to reopen in case this did not fix your situation!

**Closed by yannbf** 2021-08-20 15:48 UTC
