### ISSUE TITLE
Running `tsc --noEmit` throws an error

### ISSUE THREAD

**Issue by RiteshMakan** [storybookjs/testing-react#42] opened 2021-08-10 17:26 UTC
**Describe the bug**

I installed this add-on to our Storybook and it works like a charm. Thank you all for the awesome effort.

I have tried using Storybooks version 6.3.3 and 6.3.7

In our project repo when running `tsc --noEmit` in our codebase, after installing `"@storybook/testing-react": "^0.0.21"` I am getting the following error:

```
node_modules/@storybook/testing-react/dist/types.d.ts:1:65 - error TS2724: '"@storybook/addons"' has no exported member named 'BaseStoryFn'. Did you mean 'BaseStory'?

1 import { ArgTypes, Parameters, BaseDecorators, BaseAnnotations, BaseStoryFn as OriginalBaseStoryFn } from '@storybook/addons';

Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
**Expected behavior**
No errors

**Screenshots**
![Screenshot 2021-08-10 at 19 16 01](https://user-images.githubusercontent.com/82932397/128904846-b3283235-af4f-4731-8c62-1c76819e3d1c.png)

**Additional context**
Am I missing something in the config? 
The docs do not mention adding `'@storybook/testing-react',` to the `main.js` addons section. When I try this it has no effect.

When I inspect the file `/node_modules/@storybook/testing-react/dist/types.d.ts` on VS code, it finds that this is the case. 
<img width="1215" alt="Screenshot 2021-08-10 at 19 20 33" src="https://user-images.githubusercontent.com/82932397/128905552-b4597072-a895-46d0-adc8-d4f9c87d2775.png">

When I inspect the file `node_modules/@storybook/addons/dist/ts3.9/types.d.ts` this is the case.
<img width="648" alt="Screenshot 2021-08-10 at 19 21 57" src="https://user-images.githubusercontent.com/82932397/128905734-d1c12932-f153-4882-8d53-c27d0f76b143.png">

**Comment by yannbf** [comment] 2021-08-15 15:15
Hey @RiteshMakan thank you so much for using this library! And thank you for opening the issue.
As this is a duplicate of #41, I'll be closing this issue and giving a proper response there, hope you don't mind!

**Closed by yannbf** 2021-08-15 15:15 UTC
