### ISSUE TITLE
"Storybook preview hooks can only be called inside decorators and story functions." error

### ISSUE THREAD

**Issue by neil-morrison44** [storybookjs/testing-react#30] opened 2021-06-21 14:30 UTC
**Describe the bug**

We've got a custom addon that we've written internally to allow us to document / manipulate our i18n translations inside storybooks & we're having trouble getting it to work with this.

So far I've:
- Started to set up `@storybookjs/testing-react` (which, once we get it working will save a lot of time & be incredibly useful so thanks)
- Noticed that the decorator provided by the addon wasn't being applied (which I guess makes sense? the `.storybook/main.js` with the addon array isn't referenced anywhere)
- Thought I'd use the `setGlobalConfig` to manually add in the decorator from our addon
- Got the `Storybook preview hooks can only be called inside decorators and story functions.` error

Our decorator looks something like:

```jsx

import React, { useEffect, useState } from "react"
import { I18nContext } from "@our_stuff/i18nContext"
import I18n from "@our_stuff/i18n"
import { makeDecorator, useGlobals, useParameter } from "@storybook/addons"

export const withOurI18n = makeDecorator({
  name: "withOurI18n",
  parameterName: "i18n",
  wrapper: (storyFn, context, { parameters }) => {
    const paramI18nData = useParameter("i18n", {})
    const [{ "our-intl": intlData }] = useGlobals()
    const [i18n, setI18n] = useState(getNewI18nForData(intlData || paramI18nData))

    useEffect(() => {
      if (intlData) setI18n(I18n(intlData))
    }, [intlData])

    return <I18nContext.Provider value={i18n}>{storyFn()}</I18nContext.Provider>
  },
})
```

(it's rough & has bugs but it works when viewing one story in storybook)

Our jest.setup.js looks like:
```js
import { setGlobalConfig } from "@storybook/testing-react"
import * as globalStorybookConfig from "../.storybook/preview"
import { withOurI18n } from "@our_stuff/storybook-addon-i18n/dist/decorators/withI18n"

setGlobalConfig({ ...globalStorybookConfig, decorators: [withOurI18n] })
```

At the moment our test looks pretty much exactly like the one in the getting started documentation

Let me know if there's anything else I can provide that'd be useful

**Expected behavior**
Would expect the decorators to function the same way they do when viewing the story in the storybook.

**Comment by yannbf** [comment] 2021-06-22 21:11
Hey @neil-morrison44, thanks a lot for using this library!

I wonder if this way of writing a decorator would work without any issues, achieving the same goal:
```js
import React, { useEffect, useState } from "react"
import { I18nContext } from "@our_stuff/i18nContext"
import I18n from "@our_stuff/i18n"

export const withOurI18n = (storyFn, { parameters, globals }) => {
   const { i18n: paramI18nData = {} } = parameters
   const { "our-intl": intlData } = globals
   const [i18n, setI18n] = useState(getNewI18nForData(intlData || paramI18nData))

    useEffect(() => {
      if (intlData) setI18n(I18n(intlData))
    }, [intlData])

    return <I18nContext.Provider value={i18n}>{storyFn()}</I18nContext.Provider>
}
```

**Comment by neil-morrison44** [comment] 2021-06-22 21:39
Can confirm that using the globals / parameters from the decorator args rather than the `@storybook/addons` hooks has got me past that issue (and probably makes more sense anyway since they're right there).

Checked if it still works when done via the `makeDecorator` and it does, think there's some "don't use the decorator if the parameter is missing" stuff in `makeDecorator` that we'll probably end up using later on.

However from what I can tell the context that's being provided by the decorator isn't available to the rendered component - I've removed the complexity around globals / parameters and I am just reading values from the parameters and putting them straight into the context.

That's unrelated to the above issue so I'm happy for this one to get closed out, thanks.

I'll have a go working through what's happening with the context tomorrow - as far as I can tell it is rendering the provider with the right value but the component is still using the default context. 
Any ideas you have / hints at where to look to debug it better would be appreciated

**Comment by yannbf** [comment] 2021-08-15 15:41
> There is one thing that differs between the decorator you suggested & the one using useGlobals etc -- the useGlobals one will re-render when globals update. 

Hey @shilman any tips about this (or the issue)?

**Comment by shilman** [comment] 2021-08-15 16:38
Sounds to me like it might be a bug in testing-react. There is some extra bookkeeping that needs to happen for storybook hooks to work, and it looks like that's not happening in the composition function.

**Comment by smeevil** [comment] 2021-09-16 11:47
I'm running into the same problem using the following:

```tsx
export const Decorator = (storyFn, context) => {
  const { i18n } = useTranslation()
  useEffect(() => {
    i18n.changeLanguage(context.globals.locale)
  }, [context.globals.locale])

  return (<div>{storyFn()}</div>)
}
```

The return function normally contains a whole bunch of context providers but I removed them to keep the example short :)

**Comment by david-morris** [comment] 2022-01-27 11:36
I'm having the same error, but while viewing stories in storybook.  What is a storybook preview hook?  Is there documentation on what they are and how they are set up?

**Comment by yannbf** [comment] 2022-01-27 11:40
Hey everyone, I found the reason for this issue. The composed story does not contain Storybook specific hooks (like `useEffect` coming from `@storybook/addons`) and will fail because the hooks are not provided in the context. I'll try my best to fix it!

**Comment by dep** [comment] 2022-03-01 19:31
I'm having the same problem in what I think is a pretty simple story with actions:

```js
import React from "react";
import { Button, Menu, MenuItem } from ".";

const meta = {
  title: "1. Core Components/Menus",
  component: Menu,
  parameters: {
    design: {
      type: "figma",
      url: "https://www.figma.com/file/jh6AQcOATYpxshCcRVOQ6U/IDS---Core-Components?node-id=4658%3A41112",
    },
  },
};

function Menus() {
  const [anchorEl, setAnchorEl] = React.useState(null);

  const handleClick = event => {
    setAnchorEl(event.currentTarget);
  };

  const handleClose = () => {
    setAnchorEl(null);
  };

  return (
    <div>
      <Button
        aria-controls="simple-menu"
        aria-haspopup="true"
        onClick={handleClick}
      >
        Open Menu
      </Button>
      <Menu
        id="simple-menu"
        anchorEl={anchorEl}
        keepMounted
        open={Boolean(anchorEl)}
        onClose={handleClose}
      >
        <MenuItem onClick={handleClose}>Profile</MenuItem>
        <MenuItem onClick={handleClose}>My account</MenuItem>
        <MenuItem onClick={handleClose}>Logout</MenuItem>
      </Menu>
    </div>
  );
}

export default meta;

export { Menus };
```

Any help is appreciated.

**Comment by dep** [comment] 2022-03-03 14:27
In my case it was something inside of the  `storybook-addon-pseudo-states` add-on which was causing my stories to fail. Removing it did the trick for me:

```
- addons: ["@storybook/addon-docs", "storybook-addon-pseudo-states"],
+ addons: ["@storybook/addon-docs"],
```

**Comment by totszwai** [comment] 2022-03-04 18:35
@yannbf  Any update on this? Is there a workaround? Essentially it seems that any decorators trying to pass the context to the story will fail..

```
addDecorator((Story, context) => {
  const theme = DefaultTheme[context.globals.theme];
  return (
    <MyThemeProvider theme={theme}>
      <Story {...context} /> // <== this will cause the error
    </MyThemeProvider>
  );
});
// */

addDecorator((story) => {
  return (
    <I18NextProvider i18n={i18n}>
      {story()} // <== this would pass, but is causing some other weird behavior downstream, like the locales won't change unless I toggle the locales in the toolbar 4 times...
    </I18NextProvider>
  );
});
// */
```

**Comment by anthonyma94** [comment] 2022-03-09 18:51
I'm having the same issue when I use `useArgs` from [@storybook/client-api](https://github.com/storybookjs/storybook/tree/main/lib/client-api):

Button.stories.tsx
```tsx
import React from "react";
import { useArgs } from "@storybook/client-api";
import Button from "./Button";
import { ComponentMeta, ComponentStory } from "@storybook/react";
import { ButtonProps } from ".";

Button.defaultProps = {
  loading: false,
  variant: "contained",
  color: "primary",
  disabled: false,
};

export default {
  component: Button,
  // Any event listeners need to be manually defined
  argTypes: {
    onClick: {
      name: "onClick",
      type: { name: "function" },
      description: "onClick event",
    },
    variant: {
      name: "variant",
      type: { name: "enum" },
    },
  },
} as ComponentMeta<typeof Button>;

const ToggleTemplate: ComponentStory<typeof Button> = (args: ButtonProps) => {
  // useArgs allow for programatic changes to args (controls)
  const [_, updateArgs] = useArgs();

  const toggleFunc = () =>
    updateArgs({
      toggle: { ...args.toggle, toggleFunc, value: !args.toggle?.value },
    });

  return (
    <Button
      {...args}
      toggle={{
        ...args.toggle,
        toggleFunc,
        value: args.toggle?.value ?? false,
      }}
    />
  );
};

const Template: ComponentStory<typeof Button> = (args) => <Button {...args} />;

export const Basic = Template.bind({});
export const CustomColor = Template.bind({});
export const Loading = Template.bind({});
export const Toggle: typeof ToggleTemplate = ToggleTemplate.bind({});
export const ToggleAlt = ToggleTemplate.bind({});

Basic.args = {
  children: "Hello World",
};

CustomColor.args = {
  children: "This color is #cf0cb8",
  customColor: "#cf0cb8",
};

Loading.args = {
  children: "Loading",
  loading: true,
};

Toggle.args = {
  children: "Toggle me!",
  toggle: {
    toggleFunc: () => {},
    value: false,
  },
};

ToggleAlt.args = {
  children: "Toggle me!",
  toggle: {
    toggleFunc: () => {},
    value: true,
  },
};
```
Button.spec.tsx
```tsx
import React, { useRef, useState } from "react";
import "@testing-library/jest-dom/extend-expect";
import { render, waitFor, cleanup } from "../test-setup";
import Button, { ButtonProps } from "./Button";
import { screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { setGlobalConfig, composeStories } from "@storybook/testing-react";
import * as stories from "./Button.stories";
import * as sbPreview from "../../../.storybook/preview";

setGlobalConfig(sbPreview);

const { Toggle } = composeStories(stories);

describe("Button", () => {
  beforeEach(() => {});
  afterEach(() => {
    cleanup();
  });

  it("should change toggle view", async () => {
    const user = userEvent.setup();
    const component = render(<Toggle>Test toggle</Toggle>);
    const { rerender } = component;
    expect(component).toBeTruthy();

    const button = screen.getByRole("button");
    expect(screen.getByRole("button")).toHaveTextContent("Test toggle");
    await user.click(screen.getByRole("button"));
    rerender(<Toggle>Test toggle</Toggle>);

    expect(screen.getByRole("button")).toHaveTextContent("Cancel");
  });
});
```

Error
```
Storybook preview hooks can only be called inside decorators and story functions.

      31 | const ToggleTemplate: ComponentStory<typeof Button> = (args: ButtonProps) => {
      32 |   // useArgs allow for programatic changes to args (controls)
    > 33 |   const [_, updateArgs] = useArgs();
         |                           ^
      34 |
      35 |   const toggleFunc = () =>
      36 |     updateArgs({
```

**Comment by kgrupp** [comment] 2022-03-11 13:50
> In my case it was something inside of the `storybook-addon-pseudo-states` add-on which was causing my stories to fail. Removing it did the trick for me:
> 
> ```
> - addons: ["@storybook/addon-docs", "storybook-addon-pseudo-states"],
> + addons: ["@storybook/addon-docs"],
> ```

Adding `storybook-addon-pseudo-states` introduced the issue in my case.

```
invalidHooksError@http://localhost:9001/vendors~main.iframe.bundle.js:99401:10
useStoryContext@http://localhost:9001/vendors~main.iframe.bundle.js:99603:11
useParameter@http://localhost:9001/vendors~main.iframe.bundle.js:99611:26
withPseudoState@http://localhost:9001/vendors~main.iframe.bundle.js:267187:44
hookify/<@http://localhost:9001/vendors~main.iframe.bundle.js:99347:21
decorateStory/<@http://localhost:9001/vendors~main.iframe.bundle.js:101254:12
```

I solved the broken stories by wrapping them into a separate component and just using the component without additional hooks.

```
export const _default = () => <Default />;
const Default = () => {
  const [open, setOpen] = useState(false);
  const handleClose = (actionValue: string, args?: any[]) => {
    setOpen(false);
  };
  return (
    <MyDialog open={open} onApply={handleClose}>
  );
};
```

Not the best workaround, but I did not have many cases like that.

**Comment by uk-taniyama** [comment] 2022-03-15 10:56
useArgs->useStorybookApi:

https://github.com/storybookjs/storybook/blob/613fc4c2cb0f946566435435c34520295794a40b/lib/api/src/index.tsx#L326-L329
```
export function useStorybookApi(): API {
  const { api } = useContext(ManagerContext);
  return api;
}
```

Therefore, I think the Story should be render in the ManagerProvider.

**Comment by nahumzs** [comment] 2022-03-15 18:45
maybe unrelated to the question, but is one of the first answers when using google for this error. 

My case I clicked `cmd + "."` in vscode and instead of vscode automatically importing useEffect from `react` did it from storybook, don't know how good of an idea was named useEffect after the "real" react useEffect :P, small inconvenience.

**Comment by uk-taniyama** [comment] 2022-03-16 02:23
It worked with the following changes:

- testing-react:

1. defaultDocorateStory -> applyHooks(defaultDecorateStory)
https://github.com/storybookjs/testing-react/blob/0ea46e57292efb04c583411cd7d06daa821dc413/src/index.ts#L100
```
const decorateStory = addons.applyHooks(clientApi.defaultDecorateStory)
```

2. add hooks member for context.
https://github.com/storybookjs/testing-react/blob/0ea46e57292efb04c583411cd7d06daa821dc413/src/index.ts#L126
```
hooks: new addons.HooksContext()
```

**Comment by yannbf** [comment] 2022-03-20 12:36
This was released in [`v1.2.4`](https://github.com/storybookjs/testing-react/releases/tag/v1.2.4) with changes from the amazing contributor @uk-taniyama. Thank you!

**Closed by yannbf** 2022-03-20 12:36 UTC
Labels: bug

**Comment by terraelise** [comment] 2022-03-22 01:08
Thank you, @uk-taniyama  - upgrading immediately fixed my issue (was using useArgs).

**Comment by saltnpixels** [comment] 2022-12-20 21:21
> I'm having the same issue when I use `useArgs` from [@storybook/client-api](https://github.com/storybookjs/storybook/tree/main/lib/client-api):
> 
> Button.stories.tsx
> 
> ```tsx
> import React from "react";
> import { useArgs } from "@storybook/client-api";
> import Button from "./Button";
> import { ComponentMeta, ComponentStory } from "@storybook/react";
> import { ButtonProps } from ".";
> 
> Button.defaultProps = {
>   loading: false,
>   variant: "contained",
>   color: "primary",
>   disabled: false,
> };
> 
> export default {
>   component: Button,
>   // Any event listeners need to be manually defined
>   argTypes: {
>     onClick: {
>       name: "onClick",
>       type: { name: "function" },
>       description: "onClick event",
>     },
>     variant: {
>       name: "variant",
>       type: { name: "enum" },
>     },
>   },
> } as ComponentMeta<typeof Button>;
> 
> const ToggleTemplate: ComponentStory<typeof Button> = (args: ButtonProps) => {
>   // useArgs allow for programatic changes to args (controls)
>   const [_, updateArgs] = useArgs();
> 
>   const toggleFunc = () =>
>     updateArgs({
>       toggle: { ...args.toggle, toggleFunc, value: !args.toggle?.value },
>     });
> 
>   return (
>     <Button
>       {...args}
>       toggle={{
>         ...args.toggle,
>         toggleFunc,
>         value: args.toggle?.value ?? false,
>       }}
>     />
>   );
> };
> 
> const Template: ComponentStory<typeof Button> = (args) => <Button {...args} />;
> 
> export const Basic = Template.bind({});
> export const CustomColor = Template.bind({});
> export const Loading = Template.bind({});
> export const Toggle: typeof ToggleTemplate = ToggleTemplate.bind({});
> export const ToggleAlt = ToggleTemplate.bind({});
> 
> Basic.args = {
>   children: "Hello World",
> };
> 
> CustomColor.args = {
>   children: "This color is #cf0cb8",
>   customColor: "#cf0cb8",
> };
> 
> Loading.args = {
>   children: "Loading",
>   loading: true,
> };
> 
> Toggle.args = {
>   children: "Toggle me!",
>   toggle: {
>     toggleFunc: () => {},
>     value: false,
>   },
> };
> 
> ToggleAlt.args = {
>   children: "Toggle me!",
>   toggle: {
>     toggleFunc: () => {},
>     value: true,
>   },
> };
> ```
> 
> Button.spec.tsx
> 
> ```tsx
> import React, { useRef, useState } from "react";
> import "@testing-library/jest-dom/extend-expect";
> import { render, waitFor, cleanup } from "../test-setup";
> import Button, { ButtonProps } from "./Button";
> import { screen } from "@testing-library/react";
> import userEvent from "@testing-library/user-event";
> import { setGlobalConfig, composeStories } from "@storybook/testing-react";
> import * as stories from "./Button.stories";
> import * as sbPreview from "../../../.storybook/preview";
> 
> setGlobalConfig(sbPreview);
> 
> const { Toggle } = composeStories(stories);
> 
> describe("Button", () => {
>   beforeEach(() => {});
>   afterEach(() => {
>     cleanup();
>   });
> 
>   it("should change toggle view", async () => {
>     const user = userEvent.setup();
>     const component = render(<Toggle>Test toggle</Toggle>);
>     const { rerender } = component;
>     expect(component).toBeTruthy();
> 
>     const button = screen.getByRole("button");
>     expect(screen.getByRole("button")).toHaveTextContent("Test toggle");
>     await user.click(screen.getByRole("button"));
>     rerender(<Toggle>Test toggle</Toggle>);
> 
>     expect(screen.getByRole("button")).toHaveTextContent("Cancel");
>   });
> });
> ```
> 
> Error
> 
> ```
> Storybook preview hooks can only be called inside decorators and story functions.
> 
>       31 | const ToggleTemplate: ComponentStory<typeof Button> = (args: ButtonProps) => {
>       32 |   // useArgs allow for programatic changes to args (controls)
>     > 33 |   const [_, updateArgs] = useArgs();
>          |                           ^
>       34 |
>       35 |   const toggleFunc = () =>
>       36 |     updateArgs({
> ```

did you get this fixed? cause I'm still having same issue

**Comment by yannbf** [comment] 2023-01-11 13:28
Hey @saltnpixels, I'll try and take a look at this next week! Thanks for letting me know

**Comment by yannbf** [comment] 2023-01-16 11:20
@saltnpixels I recreated a slightly similar component (I don't have your source) and I didn't have any issues with the latest version of this library. If you still have trouble, feel free to reopen this issue, however with a reproduction, so I can take a look at it. Thanks!

**Comment by Dron007** [comment] 2023-04-14 13:53
I get this error for the following code:
```js
import { useState } from 'react'
import { useArgs } from '@storybook/store'
import { action } from '@storybook/addon-actions'
import DatetimeInput from './Index'

export default {
  component: DatetimeInput,
}

const TemplateComponent = (args, context) => {
  const [, setArgs] = useArgs()
  const [value, setValue] = useState()

  const onChange = (datetime) => {
    action('onChange')(datetime)
    setArgs({ value: datetime })
    setValue('datetime') // this line cause error
  }
  return <DatetimeInput {...args} onChange={onChange} />
}

const Template = {
  render: TemplateComponent,
  args: {
    value: 'bbb',
  },
}

export const Default = {
  ...Template,
}
```

I had to use separate `TemplateComponent` to fix ling error about hooks.
State is used because controlled components don't work in Docs in Stories block probably because `setArgs` doesn't change args there and doesn't pass value to the component. Without it controlled component doesn't update.
Storybook 7.0.4 is used.

**Comment by joriswitteman** [comment] 2023-04-27 09:10
For me, the fix was going from this style of decorators in preview.tsx:

```tsx
const MyDecorator = story => {  
  return (
    <>
      <div>Yay for decorators (and hooks!)<div>
      {story()}
    </>
  )  
}
```

to this style: 

```tsx
const MyDecorator = Story => {  
  return (
    <>
      <div>Yay for decorators (and hooks!)<div>
      <Story />
    </>
  )  
}
```

All the decorators started working again, and the error about hooks disappeared.

**Comment by Thremulant** [comment] 2023-05-10 16:15
> For me, the fix was going from this style of decorators in preview.tsx:
> 
> ```tsx
> const MyDecorator = story => {  
>   return (
>     <>
>       <div>Yay for decorators (and hooks!)<div>
>       {story()}
>     </>
>   )  
> }
> ```
> 
> to this style:
> 
> ```tsx
> const MyDecorator = Story => {  
>   return (
>     <>
>       <div>Yay for decorators (and hooks!)<div>
>       <Story />
>     </>
>   )  
> }
> ```
> 
> All the decorators started working again, and the error about hooks disappeared.

We had the exact same problem after updating to `7.0.7`. But the solution was exactly the opposite:
It used to be:
````js
  decorators: [
    (Story) => {
      return (
        <>
            <Story />
        </>
      );
    },
  ],
````
And when I changed it to:

````javascript
  decorators: [
    (story) => {
      return (
        <>
            {story()}
        </>
      );
    },
  ],
````
It worked

**Comment by adnanjpg** [comment] 2023-07-20 16:15
In my case I was using `react`'s native hooks `useState` and `useEffect` imported from `react`. the solution was to import them from `@storybook/client-api` instead.

before:
```
import { useState, useEffect } from "react"
import { useArgs} from "@storybook/client-api"
```

after:
```
import { useArgs, useState, useEffect } from "@storybook/client-api"
```

**Comment by evad1n** [comment] 2023-07-27 22:07
I tried all the above solutions and none worked for me.

It's strange because I had 2 projects using identical `preview.tsx` files. The one that wasn't working was using nextjs, versus just webpack which worked fine.

Mine refused to work until I did this:

```ts
import { addons } from '@storybook/preview-api';

const channel = addons.getChannel();

const withTheme: Decorator = (Story, context) => {
  // const [globals, updateGlobals] = useGlobals();

  const globals = context.globals;

  const updateGlobals = () => {
    channel.emit('updateGlobals', { globals: { 'your-global': 'updated-value' } });
  }
  ....
}
```

I guess this gets around it throwing errors somewhere inside their hook which probably isn't ideal, but this was the only thing that worked.

**Comment by rmrth** [comment] 2023-07-29 00:15
it seems to work

**Comment by SergeyRoyt** [comment] 2024-01-22 11:00
For me the issue in Storybook 7 was related to `withThemeByClassName` hook from [@storybook/addon-themes](https://storybook.js.org/addons/@storybook/addon-themes), managed to solve it
https://stackoverflow.com/a/77859321/7226874

**Comment by SergeyRoyt** [comment] 2024-01-22 11:00
For me the issue in Storybook 7 was related to `withThemeByClassName` hook from [@storybook/addon-themes](https://storybook.js.org/addons/@storybook/addon-themes), managed to solve it
https://stackoverflow.com/a/77859321/7226874
