### ISSUE TITLE
Using setGlobalConfig remove window global overrides from test setup

### ISSUE THREAD

**Issue by soullivaneuh** [storybookjs/testing-react#114] opened 2022-08-22 15:33 UTC
**Describe the bug**

Given the following `.storybook/preview.ts` file:

<details>

```typescript
/* eslint-disable no-use-before-define, react/jsx-filename-extension */
import { Parameters, DecoratorFn } from '@storybook/react';
import { create, ThemeVars } from '@storybook/theming';
import {
  initialize as mswInitialize,
  mswDecorator,
} from 'msw-storybook-addon';
import serverHandlers from '../src/server/handlers';
import { DocsContainer, StoryDecorator } from './components';

const companyTheme: Partial<ThemeVars> = {
  brandTitle: 'Company Console',
  brandImage: 'https://design.company.dev/img/logo/text.svg',
};

export const parameters: Parameters = {
  actions: {
    argTypesRegex: '^on[A-Z].*',
  },
  docs: {
    container: DocsContainer,
  },
  darkMode: {
    dark: create({
      base: 'dark',
      ...companyTheme,
    }),
    light: create({
      base: 'light',
      ...companyTheme,
    }),
  },
  msw: {
    handlers: serverHandlers,
  },
};

export const globalTypes = {
  locale: {
    name: 'Locale',
    description: 'Internationalization locale',
    defaultValue: 'en',
    toolbar: {
      icon: 'globe',
      items: [
        {
          value: 'en',
          right: '🇺🇸',
          title: 'English',
        },
        {
          value: 'fr',
          right: '🇫🇷',
          title: 'Français',
        },
      ],
    },
  },
};

// @see https://github.com/mswjs/msw-storybook-addon/issues/59#issuecomment-974683387
if (!global.test) {
  mswInitialize();
}

export const decorators: DecoratorFn[] = [
  // @ts-expect-error expected config fetched from setup documentation.
  mswDecorator,
  StoryDecorator,
];
```

</details>

And the following `src/setupTests.ts` file:

<details>

```typescript
// jest-dom adds custom jest matchers for asserting on DOM nodes.
// allows you to do things like:
// expect(element).toHaveTextContent(/react/i)
// learn more: https://github.com/testing-library/jest-dom
import '@testing-library/jest-dom';
import {
  createMatchMedia,
  server,
} from './test-utils';

window.matchMedia = createMatchMedia();

// @see https://react.i18next.com/misc/testing
jest.mock('react-i18next', () => {
  // @see https://github.com/facebook/jest/issues/2567
  // eslint-disable-next-line @typescript-eslint/no-var-requires, global-require
  const { i18n } = require('./test-utils');

  return {
    useTranslation: () => ({
      t: (str: string) => str,
      i18n,
    }),
    // Needed to make storyshots working with the locale global option.
    // @see https://github.com/i18next/i18next/issues/1426#issuecomment-828656983
    initReactI18next: {
      type: '3rdParty',
      init: jest.fn(),
    },
  };
});

beforeAll(() => {
  // Enable mocking.
  server.listen();
});

afterEach(() => {
  server.resetHandlers();
});

afterAll(() => {
  // Clean up once the tests are done.
  server.close();
});
```

</details>

If I add the `setGlobalConfig` call on it:

<details>

```diff
diff --git a/src/setupTests.ts b/src/setupTests.ts
index 4d462b6..341c29b 100644
--- a/src/setupTests.ts
+++ b/src/setupTests.ts
@@ -3,11 +3,15 @@
 // expect(element).toHaveTextContent(/react/i)
 // learn more: https://github.com/testing-library/jest-dom
 import '@testing-library/jest-dom';
+import { setGlobalConfig } from '@storybook/testing-react';
+import * as globalStorybookConfig from '../.storybook/preview'
 import {
   createMatchMedia,
   server,
 } from './test-utils';
 
+// setGlobalConfig(globalStorybookConfig);
+
 window.matchMedia = createMatchMedia();
 
 // @see https://react.i18next.com/misc/testing
```

</details>

I got the following error on any current test:

```
  ● Test suite failed to run

    TypeError: window.matchMedia is not a function

      4 |   DocsContainerProps,
      5 | } from '@storybook/addon-docs';
    > 6 | import { useDarkMode } from 'storybook-dark-mode';
        | ^
      7 | import { themes } from '@storybook/theming';
      8 |
      9 | // @see https://github.com/hipstersmoothie/storybook-dark-mode/issues/127#issuecomment-802018811
```

So I assume the `window.matchMedia` function, I defined is somewhat override by calling `setGlobalConfig`.

Looks similar to #34, however, I didn't defined any `window.matchMedia` function on my `preview.ts` file.

**Comment by yannbf** [comment] 2022-11-07 08:45
Hey @soullivaneuh thanks for opening this issue! I am not sure what can be causing this, I'd love to see a reproduction repo so I can debug it.

If the error is `window.matchMedia is not a function`, it's probably happening in a place that is trying to call it like `window.matchMedia('(max-width: 600px)')` and maybe that is being called **before** the mocks are set? For instance, it might be running as part of any of your imports from any of your files. Also, I don't know what `createMatchMedia` looks like.

If this is indeed the cause, maybe you'll have to `require` your `../.storybook/preview` config after you set the mocks?

**Comment by yannbf** [comment] 2023-01-11 13:31
It's been quite some time, I'll be closing the issue if you don't mind, and once you have a reproduction I can take a look at, I'm happy to do so. Thank you!

**Closed by yannbf** 2023-01-11 13:31 UTC
Labels: question, needs reproduction
